<a name="menu"></a>
<div id="menu">
	<div class="pure-menu">
		<font size="3">Winds MENU</font>
		<ul style="list-style-type: none">
		<font size="2">
			<li><a href="./index.html">ホーム</a></li>
			<li><a href="./intro.html">楽団紹介</a></li>
			<li><a href="./30thconcert.html">演奏会のご案内</a></li>
			<li><a href="./history.html">これまでの活動</a></li>
			<li><a href="./schedule.html">練習日程</a></li>
			<li><a href="./contact.html">お問い合わせ</a></li>
			<li><a href="./member.html">団員専用ページ</a></li>
		</font>
	</ul>
	</div>
</div>
