<?php

	# here type page details
	$page_title = "事務局よりお知らせ｜ザ・ウィンド・アンサンブル";
	$head_title = "事務局よりお知らせ";

	$title = [

	];

	$contents = [

	];

# contents head html documents
	$contents_head_pc = <<< EOM
	<div class="header">
		<p>
		<h1>$head_title</h1>
		<h2>　</h2>
		</p>
	</div>
EOM;

	$contents_head_mb = <<< EOM
        <div class="header">
			<p>
            <center><font size="5">$head_title</font></center>
			</p>
        </div>
EOM;

?>
