第31回定期演奏会参考音源
contents/audio/source_2018winds
三日月の舞 - 麗奈 Trumpet Solo Ver(松田彬人)<>Crescent Moon Dance Reina Solo.mp3
三日月の舞 - 香織 Trumpet Solo Ver(松田彬人)<>Crescent Moon Dance Kaori Solo.mp3
三日月の舞 - 関西大会突破 Ver(松田彬人)<>Crescent Moon Dance Kansai Competition.mp3
大草原の歌(R.ミッチェル)<>Song of the Prairie.mp3
喜びの音楽を奏でて！(J.スウェアリンジェン)<>Make a Joyful Noise.mp3
ウィズ・ハート・アンド・ヴォイス(D.ギリングハム)<>With Heart and Voice.mp3
ウィズ・ハート・アンド・ヴォイス(D.ギリングハム) - 事務局推奨<>With Heart and Voice 2.mp3
アルセナール(J.ヴァンデルロースト) - 大阪市音<>Arsenal.mp3
メキシコの祭り 1. プレリュードとアズテックダンス - H.ダン, ダラス・ウィンド・シンフォニー(O.リード)<>Dallas Wind Symphony - Howard Dunn - La Fiesta Mexicana - 1. Prelude and Aztec Dance.mp3
メキシコの祭り 2. ミサ - H.ダン, ダラス・ウィンド・シンフォニー(O.リード)<>Dallas Wind Symphony - Howard Dunn - La Fiesta Mexicana - 2. Mass.mp3
メキシコの祭り 3. カーニバル - H.ダン, ダラス・ウィンド・シンフォニー(O.リード)<>Dallas Wind Symphony - Howard Dunn - La Fiesta Mexicana - 3. Carnival.mp3
メキシコの祭り 1. プレリュードとアズテックダンス - アメリカ海兵隊バンド(O.リード)<>USMC Band - La Fiesta Mexicana - 1. Prelude and Aztec Dance.mp3
メキシコの祭り 2. ミサ - アメリカ海兵隊バンド(O.リード)<>USMC Band - La Fiesta Mexicana - 2. Mass.mp3
メキシコの祭り 3. カーニバル - アメリカ海兵隊バンド(O.リード)<>USMC Band - La Fiesta Mexicana - 3. Carnival.mp3
メキシコの祭り 1. プレリュードとアズテックダンス - 野中図洋和, 陸上自衛隊中央音楽隊(O.リード)<>JSDF - Toyokazu nonaka - La Fiesta Mexicana - 1. Prelude and Aztec Dance.mp3
メキシコの祭り 2. ミサ - 野中図洋和, 陸上自衛隊中央音楽隊(O.リード)<>JSDF - Toyokazu nonaka - La Fiesta Mexicana - 2. Mass.mp3
メキシコの祭り 3. カーニバル - 野中図洋和, 陸上自衛隊中央音楽隊(O.リード)<>JSDF - Toyokazu nonaka - La Fiesta Mexicana - 3. Carnival.mp3
メキシコの祭り 1. プレリュードとアズテックダンス - F.フェネル, 東京佼成ウィンドオーケストラ(O.リード)<>Tokyo Kosei - Fennell - La Fiesta Mexicana - 1. Prelude and Aztec Dance.mp3
メキシコの祭り 2. ミサ - F.フェネル, 東京佼成ウィンドオーケストラ(O.リード)<>Tokyo Kosei - Fennell - La Fiesta Mexicana - 2. Mass.mp3
メキシコの祭り 3. カーニバル - F.フェネル, 東京佼成ウィンドオーケストラ(O.リード)<>Tokyo Kosei - Fennell - La Fiesta Mexicana - 3. Carnival.mp3
マーチ「潮煙」(上岡洋一)<>Shiokemuri.mp3
狂詩曲「ノヴェナ」(J.スウェアリンジェン)<>Novena.mp3
ブロックM - ザ・ウィンド・アンサンブル第23回定期演奏会<>Block M.mp3
