ザ・ウィンド・アンサンブルへようこそ！
<meta name="description" content="新潟県長岡市で活動している吹奏楽団ザ・ウィンド・アンサンブルのホームページです。年2回、長岡リリックホール周辺にて演奏会を企画・開催しています。"><><meta name="keywords" content="ウィンズ,ウインズ,長岡市,nagaoka,リリックホール,新潟県,ザウィンドアンサンブル,ザ・ウィンド・アンサンブル,ザウインドアンサンブル,ザ・ウインド・アンサンブル,吹奏楽,winds,thewindensemble">
reset.css<>menu.css<>style.css
0
//bread
<>
./img/top_img.jpg
ご挨拶<>　ザ・ウィンド・アンサンブルのホームページをご覧頂きありがとうございます。<br>　当団体は、1986年11月に長岡交響楽団金管奏者を中心とした長岡ブラスアンサンブルが母体となり新潟県内外の音楽好きな有志が集まって結成された社会人バンドです。<br>年2回開かれる演奏会を通して吹奏楽の楽しさを広めて行きたいと思っております。<br>　楽しい音楽の輪が広がりますように。
演奏会情報<><span class="over">第31回定期演奏会を開催いたします。<br>詳細は<a href="31stconcert.html">こちら</a></span>
コンテンツ<><h3><a href="intro">楽団紹介</a></h3><p class="follow">当楽団の紹介はこちら</p><h3><a href="30thconcert">演奏会のご案内</a></h3><p class="follow">直近の演奏会のご案内はこちら</p><h3><a href="history">これまでの活動</a></h3><p class="follow">ウィンズの歴史について</p><h3><a href="schedule">練習日程</a></h3><p class="follow">練習日程について</p><h3><a href="bbs">掲示板</a></h3><p class="follow">ご自由にお書きください</p><h3><a href="contact">お問い合わせ</a></h3><p class="follow">当楽団へのお問い合わせはこちらから</p><h3><a href="login">団員専用</a></h3><p class="follow">こちらは団員専用ページとなっております</p>
