演奏会情報｜ザ・ウィンド・アンサンブル
<meta name="description" content="ザ・ウィンド・アンサンブル(新潟県長岡市)の直近の演奏会情報です。"><><meta name="keywords" content="ウィンズ,ウインズ,長岡市,nagaoka,リリックホール,新潟県,ザウィンドアンサンブル,ザ・ウィンド・アンサンブル,ザウインドアンサンブル,ザ・ウインド・アンサンブル,吹奏楽,winds,thewindensemble">
reset.css<>menu.css<>style.css<>mini2017.css
0
//bread
演奏会のご案内<>
./img/2017mini/spring_title.png
<><!--<img src="./img/baloon.png" class="concert_spring_img">--><img src="./img/2017mini/rainbow3.png" class="concert_spring_rainbow">
終演いたしました<>2017年春のミニコンサートは終演いたしました。<br>ご来場くださいました皆さま、ありがとうございました。
春のミニコンサート<>場所: 長岡リリックホール 「ポケットステージ」<br>日時: 2017年5月13日(土) 14:00ごろ開演<br>入場無料です！
プログラム<>・前前前世<br>・恋<br>・DREAM SOLISTER<br>　ほかポップス・アニメソングなど…
アクセス<>所在: 〒940-2108　新潟県長岡市千秋3丁目1356番地6<br>長岡リリックホール コンサートホール<br>リリックホールのWebサイトは<a href="http://www.nagaoka-caf.or.jp/" target="_blank">こちら</a><br>交通のご案内<br>●JR長岡駅大手口<br>- 8番線から中央循環バスで、（内回り／近代美術館、外回り／ハイブ長岡）バス停下車、徒歩3分。<br>- 2番線から（日赤病院経由）江陽団地行きバスで、ハイブ長岡バス停下車、徒歩3分。<br>- 2番線から江陽環状線バスで、（外回り／ハイブ長岡）バス停下車、徒歩3分。<br>- 2番線から（日赤病院経由）出雲崎行きバスで、近代美術館バス停下車、徒歩3分。<br>●長岡インターチェンジ（関越・北陸自動車道）から車で約10分。<br><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3166.822865760664!2d138.82925099999997!3d37.46490400000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5ff5a990fc127773%3A0x716affcc8b27a1e3!2z6ZW35bKh44Oq44Oq44OD44Kv44Ob44O844Or!5e0!3m2!1sja!2sjp!4v1439099629551" frameborder="0" style="border:0" allowfullscreen></iframe><img src="img/2017mini/spring_footer.png">
