練習日程｜ザ・ウィンド・アンサンブル
<meta name="description" content="ザ・ウィンド・アンサンブル(新潟県長岡市)の練習日一覧です。"><><meta name="keywords" content="ウィンズ,ウインズ,長岡市,nagaoka,リリックホール,新潟県,ザウィンドアンサンブル,ザ・ウィンド・アンサンブル,ザウインドアンサンブル,ザ・ウインド・アンサンブル,吹奏楽,winds,thewindensemble">
reset.css<>menu.css<>style.css<>schedule.css
0
//bread
練習日程<>
./img/000007.jpg
練習について<>練習は主に<a href="http://www.nagaoka-caf.or.jp/" target="_blank">リリックホール</a>のスタジオにて行っております。基本的に第5スタジオにて毎週土曜日18時から22時まで練習を行います。本番が近くなると、第1スタジオやコンサートホールなどを利用して練習しています。
